// <auto-generated />
using CSHomeworkAPI.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace CSHomeworkAPI.Migrations
{
    [DbContext(typeof(CSHomeworkContext))]
    [Migration("20171111125157_CSHomeworkDBAddQuestionEntity")]
    partial class CSHomeworkDBAddQuestionEntity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CSHomeworkAPI.Entities.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("QuestionId");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("CSHomeworkAPI.Entities.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("Cols");

                    b.Property<bool>("CorrectAnswer");

                    b.Property<bool>("Explanation");

                    b.Property<int>("Max");

                    b.Property<int>("MaxLength");

                    b.Property<int>("Min");

                    b.Property<int>("MinLength");

                    b.Property<string>("Pattern")
                        .HasMaxLength(255);

                    b.Property<string>("PlaceHolder")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("Rows");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.HasKey("Id");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("CSHomeworkAPI.Entities.Answer", b =>
                {
                    b.HasOne("CSHomeworkAPI.Entities.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
